// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9ekqK0BVKB6fpy-4Rps5bdsJUHeC0yNg',
    appId: '1:227646681291:web:c0231e8bb8466eec026b4e',
    messagingSenderId: '227646681291',
    projectId: 'mayan-828f9',
    authDomain: 'mayan-828f9.firebaseapp.com',
    storageBucket: 'mayan-828f9.firebasestorage.app',
    measurementId: 'G-QNR0XV84V7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4O04_6edwreLwbiko4LW3DiY6VNnEvPA',
    appId: '1:227646681291:android:31edb51b1e4e1d5f026b4e',
    messagingSenderId: '227646681291',
    projectId: 'mayan-828f9',
    storageBucket: 'mayan-828f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvuhrXcLkkfvocNKPt8biC5TdsT5bTfXI',
    appId: '1:227646681291:ios:b1799c1901ceaa86026b4e',
    messagingSenderId: '227646681291',
    projectId: 'mayan-828f9',
    storageBucket: 'mayan-828f9.firebasestorage.app',
    iosBundleId: 'com.example.mayan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvuhrXcLkkfvocNKPt8biC5TdsT5bTfXI',
    appId: '1:227646681291:ios:b1799c1901ceaa86026b4e',
    messagingSenderId: '227646681291',
    projectId: 'mayan-828f9',
    storageBucket: 'mayan-828f9.firebasestorage.app',
    iosBundleId: 'com.example.mayan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9ekqK0BVKB6fpy-4Rps5bdsJUHeC0yNg',
    appId: '1:227646681291:web:e51a4325297775b6026b4e',
    messagingSenderId: '227646681291',
    projectId: 'mayan-828f9',
    authDomain: 'mayan-828f9.firebaseapp.com',
    storageBucket: 'mayan-828f9.firebasestorage.app',
    measurementId: 'G-0XX9KPPED5',
  );
}
